
/* Nodes representing parameter channels in workflow */

/* Edges representing connections between programs and channels */
CleanFarmersMarketDataWithOpenRefine -> "FarmersMarkets-Address.csv"
CleanFarmersMarketDataWithOpenRefine -> "FarmersMarkets-Products.csv"
CleanFarmersMarketDataWithOpenRefine -> "FarmersMarkets-SocialMedia.csv"
"farmersmarkets.csv" -> CleanFarmersMarketDataWithOpenRefine
CleanFarmersMarketDataActivties -> CleanFarmersMarketDataWithOpenRefine
SQLOperationsOnfarmersmarketsAddress -> Farmers_Markets_Address
"FarmersMarkets-Address.csv" -> SQLOperationsOnfarmersmarketsAddress
FarmersMarketsAdressImport -> SQLOperationsOnfarmersmarketsAddress
SQLOperationsOnfarmersmarketsProducts -> Farmers_Markets_Products
"FarmersMarkets-Products.csv" -> SQLOperationsOnfarmersmarketsProducts
FarmersMarketsProductsImport -> SQLOperationsOnfarmersmarketsProducts
SQLOperationsOnfarmersmarketsSocialMedia -> Farmers_Markets_SocialMedia
"FarmersMarkets-SocialMedia.csv" -> SQLOperationsOnfarmersmarketsSocialMedia
FarmersMarketsSocialMediaImport -> SQLOperationsOnfarmersmarketsSocialMedia
SQLConstrainsValidations -> Farmers_Markets_Address_Final
SQLConstrainsValidations -> Farmers_Markets_Products_Final
SQLConstrainsValidations -> Farmers_Markets_SocialMedia_Final
Farmers_Markets_Address -> SQLConstrainsValidations
Farmers_Markets_Products -> SQLConstrainsValidations
Farmers_Markets_SocialMedia -> SQLConstrainsValidations
IntegrityConstraint_FunctionalDependenciesScript -> SQLConstrainsValidations

/* End of double cluster for drawing box around nodes in workflow */
}}

/* Style for nodes representing workflow input ports */
node[shape=circle style="rounded,filled" fillcolor="#FFFFFF" peripheries=1 fontname=Helvetica width=0.2]

/* Nodes representing workflow input ports */
"farmersmarkets.csv_input_port" [label=""]

/* Style for nodes representing workflow output ports */
node[shape=circle style="rounded,filled" fillcolor="#FFFFFF" peripheries=1 fontname=Helvetica width=0.2]

/* Nodes representing workflow output ports */
Farmers_Markets_Address_Final_output_port [label=""]
Farmers_Markets_Products_Final_output_port [label=""]
Farmers_Markets_SocialMedia_Final_output_port [label=""]

/* Edges from input ports to channels */
"farmersmarkets.csv_input_port" -> "farmersmarkets.csv"

/* Edges from channels to output ports */
Farmers_Markets_Address_Final -> Farmers_Markets_Address_Final_output_port
Farmers_Markets_Products_Final -> Farmers_Markets_Products_Final_output_port
Farmers_Markets_SocialMedia_Final -> Farmers_Markets_SocialMedia_Final_output_port

/* End of top-level graph */
}
